/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.elasticinbox.pipe.avro;  
@SuppressWarnings("all")
public class AvroMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroMessage\",\"namespace\":\"com.elasticinbox.pipe.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"date\",\"type\":\"long\",\"default\":0},{\"name\":\"size\",\"type\":\"long\",\"default\":0},{\"name\":\"location\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"userId\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"labels\",\"type\":{\"type\":\"array\",\"items\":\"int\"},\"default\":[]},{\"name\":\"markers\",\"type\":{\"type\":\"array\",\"items\":\"int\"},\"default\":[]},{\"name\":\"properties\",\"type\":{\"type\":\"map\",\"values\":\"long\"},\"default\":{}},{\"name\":\"original\",\"type\":[\"string\",\"null\"]},{\"name\":\"from\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroAddress\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"address\",\"type\":\"string\"}]}},\"default\":[]},{\"name\":\"to\",\"type\":{\"type\":\"array\",\"items\":\"AvroAddress\"},\"default\":[]},{\"name\":\"cc\",\"type\":{\"type\":\"array\",\"items\":\"AvroAddress\"},\"default\":[]},{\"name\":\"bcc\",\"type\":{\"type\":\"array\",\"items\":\"AvroAddress\"},\"default\":[]},{\"name\":\"subject\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"plainBody\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"htmlBody\",\"type\":\"string\",\"default\":\"\"}]}");
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public long date;
  @Deprecated public long size;
  @Deprecated public java.lang.CharSequence location;
  @Deprecated public java.lang.CharSequence userId;
  @Deprecated public java.util.List<java.lang.Integer> labels;
  @Deprecated public java.util.List<java.lang.Integer> markers;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Long> properties;
  @Deprecated public java.lang.CharSequence original;
  @Deprecated public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> from;
  @Deprecated public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> to;
  @Deprecated public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> cc;
  @Deprecated public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> bcc;
  @Deprecated public java.lang.CharSequence subject;
  @Deprecated public java.lang.CharSequence plainBody;
  @Deprecated public java.lang.CharSequence htmlBody;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return date;
    case 2: return size;
    case 3: return location;
    case 4: return userId;
    case 5: return labels;
    case 6: return markers;
    case 7: return properties;
    case 8: return original;
    case 9: return from;
    case 10: return to;
    case 11: return cc;
    case 12: return bcc;
    case 13: return subject;
    case 14: return plainBody;
    case 15: return htmlBody;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: date = (java.lang.Long)value$; break;
    case 2: size = (java.lang.Long)value$; break;
    case 3: location = (java.lang.CharSequence)value$; break;
    case 4: userId = (java.lang.CharSequence)value$; break;
    case 5: labels = (java.util.List<java.lang.Integer>)value$; break;
    case 6: markers = (java.util.List<java.lang.Integer>)value$; break;
    case 7: properties = (java.util.Map<java.lang.CharSequence,java.lang.Long>)value$; break;
    case 8: original = (java.lang.CharSequence)value$; break;
    case 9: from = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>)value$; break;
    case 10: to = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>)value$; break;
    case 11: cc = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>)value$; break;
    case 12: bcc = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>)value$; break;
    case 13: subject = (java.lang.CharSequence)value$; break;
    case 14: plainBody = (java.lang.CharSequence)value$; break;
    case 15: htmlBody = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'date' field.
   */
  public java.lang.Long getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.Long value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'size' field.
   */
  public java.lang.Long getSize() {
    return size;
  }

  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(java.lang.Long value) {
    this.size = value;
  }

  /**
   * Gets the value of the 'location' field.
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'labels' field.
   */
  public java.util.List<java.lang.Integer> getLabels() {
    return labels;
  }

  /**
   * Sets the value of the 'labels' field.
   * @param value the value to set.
   */
  public void setLabels(java.util.List<java.lang.Integer> value) {
    this.labels = value;
  }

  /**
   * Gets the value of the 'markers' field.
   */
  public java.util.List<java.lang.Integer> getMarkers() {
    return markers;
  }

  /**
   * Sets the value of the 'markers' field.
   * @param value the value to set.
   */
  public void setMarkers(java.util.List<java.lang.Integer> value) {
    this.markers = value;
  }

  /**
   * Gets the value of the 'properties' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Long> getProperties() {
    return properties;
  }

  /**
   * Sets the value of the 'properties' field.
   * @param value the value to set.
   */
  public void setProperties(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
    this.properties = value;
  }

  /**
   * Gets the value of the 'original' field.
   */
  public java.lang.CharSequence getOriginal() {
    return original;
  }

  /**
   * Sets the value of the 'original' field.
   * @param value the value to set.
   */
  public void setOriginal(java.lang.CharSequence value) {
    this.original = value;
  }

  /**
   * Gets the value of the 'from' field.
   */
  public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getFrom() {
    return from;
  }

  /**
   * Sets the value of the 'from' field.
   * @param value the value to set.
   */
  public void setFrom(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
    this.from = value;
  }

  /**
   * Gets the value of the 'to' field.
   */
  public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getTo() {
    return to;
  }

  /**
   * Sets the value of the 'to' field.
   * @param value the value to set.
   */
  public void setTo(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
    this.to = value;
  }

  /**
   * Gets the value of the 'cc' field.
   */
  public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getCc() {
    return cc;
  }

  /**
   * Sets the value of the 'cc' field.
   * @param value the value to set.
   */
  public void setCc(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
    this.cc = value;
  }

  /**
   * Gets the value of the 'bcc' field.
   */
  public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getBcc() {
    return bcc;
  }

  /**
   * Sets the value of the 'bcc' field.
   * @param value the value to set.
   */
  public void setBcc(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
    this.bcc = value;
  }

  /**
   * Gets the value of the 'subject' field.
   */
  public java.lang.CharSequence getSubject() {
    return subject;
  }

  /**
   * Sets the value of the 'subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.CharSequence value) {
    this.subject = value;
  }

  /**
   * Gets the value of the 'plainBody' field.
   */
  public java.lang.CharSequence getPlainBody() {
    return plainBody;
  }

  /**
   * Sets the value of the 'plainBody' field.
   * @param value the value to set.
   */
  public void setPlainBody(java.lang.CharSequence value) {
    this.plainBody = value;
  }

  /**
   * Gets the value of the 'htmlBody' field.
   */
  public java.lang.CharSequence getHtmlBody() {
    return htmlBody;
  }

  /**
   * Sets the value of the 'htmlBody' field.
   * @param value the value to set.
   */
  public void setHtmlBody(java.lang.CharSequence value) {
    this.htmlBody = value;
  }

  /** Creates a new AvroMessage RecordBuilder */
  public static com.elasticinbox.pipe.avro.AvroMessage.Builder newBuilder() {
    return new com.elasticinbox.pipe.avro.AvroMessage.Builder();
  }
  
  /** Creates a new AvroMessage RecordBuilder by copying an existing Builder */
  public static com.elasticinbox.pipe.avro.AvroMessage.Builder newBuilder(com.elasticinbox.pipe.avro.AvroMessage.Builder other) {
    return new com.elasticinbox.pipe.avro.AvroMessage.Builder(other);
  }
  
  /** Creates a new AvroMessage RecordBuilder by copying an existing AvroMessage instance */
  public static com.elasticinbox.pipe.avro.AvroMessage.Builder newBuilder(com.elasticinbox.pipe.avro.AvroMessage other) {
    return new com.elasticinbox.pipe.avro.AvroMessage.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroMessage>
    implements org.apache.avro.data.RecordBuilder<AvroMessage> {

    private java.lang.CharSequence id;
    private long date;
    private long size;
    private java.lang.CharSequence location;
    private java.lang.CharSequence userId;
    private java.util.List<java.lang.Integer> labels;
    private java.util.List<java.lang.Integer> markers;
    private java.util.Map<java.lang.CharSequence,java.lang.Long> properties;
    private java.lang.CharSequence original;
    private java.util.List<com.elasticinbox.pipe.avro.AvroAddress> from;
    private java.util.List<com.elasticinbox.pipe.avro.AvroAddress> to;
    private java.util.List<com.elasticinbox.pipe.avro.AvroAddress> cc;
    private java.util.List<com.elasticinbox.pipe.avro.AvroAddress> bcc;
    private java.lang.CharSequence subject;
    private java.lang.CharSequence plainBody;
    private java.lang.CharSequence htmlBody;

    /** Creates a new Builder */
    private Builder() {
      super(com.elasticinbox.pipe.avro.AvroMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.elasticinbox.pipe.avro.AvroMessage.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing AvroMessage instance */
    private Builder(com.elasticinbox.pipe.avro.AvroMessage other) {
            super(com.elasticinbox.pipe.avro.AvroMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = (java.lang.Long) data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.size)) {
        this.size = (java.lang.Long) data().deepCopy(fields()[2].schema(), other.size);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.location)) {
        this.location = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.location);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.userId)) {
        this.userId = (java.lang.CharSequence) data().deepCopy(fields()[4].schema(), other.userId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.labels)) {
        this.labels = (java.util.List<java.lang.Integer>) data().deepCopy(fields()[5].schema(), other.labels);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.markers)) {
        this.markers = (java.util.List<java.lang.Integer>) data().deepCopy(fields()[6].schema(), other.markers);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.properties)) {
        this.properties = (java.util.Map<java.lang.CharSequence,java.lang.Long>) data().deepCopy(fields()[7].schema(), other.properties);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.original)) {
        this.original = (java.lang.CharSequence) data().deepCopy(fields()[8].schema(), other.original);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.from)) {
        this.from = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) data().deepCopy(fields()[9].schema(), other.from);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.to)) {
        this.to = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) data().deepCopy(fields()[10].schema(), other.to);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.cc)) {
        this.cc = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) data().deepCopy(fields()[11].schema(), other.cc);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.bcc)) {
        this.bcc = (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) data().deepCopy(fields()[12].schema(), other.bcc);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.subject)) {
        this.subject = (java.lang.CharSequence) data().deepCopy(fields()[13].schema(), other.subject);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.plainBody)) {
        this.plainBody = (java.lang.CharSequence) data().deepCopy(fields()[14].schema(), other.plainBody);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.htmlBody)) {
        this.htmlBody = (java.lang.CharSequence) data().deepCopy(fields()[15].schema(), other.htmlBody);
        fieldSetFlags()[15] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'date' field */
    public java.lang.Long getDate() {
      return date;
    }
    
    /** Sets the value of the 'date' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setDate(long value) {
      validate(fields()[1], value);
      this.date = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'date' field has been set */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'date' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearDate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'size' field */
    public java.lang.Long getSize() {
      return size;
    }
    
    /** Sets the value of the 'size' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setSize(long value) {
      validate(fields()[2], value);
      this.size = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'size' field has been set */
    public boolean hasSize() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'size' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearSize() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'location' field */
    public java.lang.CharSequence getLocation() {
      return location;
    }
    
    /** Sets the value of the 'location' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.location = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'location' field has been set */
    public boolean hasLocation() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'location' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearLocation() {
      location = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'userId' field */
    public java.lang.CharSequence getUserId() {
      return userId;
    }
    
    /** Sets the value of the 'userId' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.userId = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'userId' field has been set */
    public boolean hasUserId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'userId' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'labels' field */
    public java.util.List<java.lang.Integer> getLabels() {
      return labels;
    }
    
    /** Sets the value of the 'labels' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setLabels(java.util.List<java.lang.Integer> value) {
      validate(fields()[5], value);
      this.labels = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'labels' field has been set */
    public boolean hasLabels() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'labels' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearLabels() {
      labels = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'markers' field */
    public java.util.List<java.lang.Integer> getMarkers() {
      return markers;
    }
    
    /** Sets the value of the 'markers' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setMarkers(java.util.List<java.lang.Integer> value) {
      validate(fields()[6], value);
      this.markers = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'markers' field has been set */
    public boolean hasMarkers() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'markers' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearMarkers() {
      markers = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'properties' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Long> getProperties() {
      return properties;
    }
    
    /** Sets the value of the 'properties' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setProperties(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
      validate(fields()[7], value);
      this.properties = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'properties' field has been set */
    public boolean hasProperties() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'properties' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearProperties() {
      properties = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'original' field */
    public java.lang.CharSequence getOriginal() {
      return original;
    }
    
    /** Sets the value of the 'original' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setOriginal(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.original = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'original' field has been set */
    public boolean hasOriginal() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'original' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearOriginal() {
      original = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'from' field */
    public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getFrom() {
      return from;
    }
    
    /** Sets the value of the 'from' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setFrom(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
      validate(fields()[9], value);
      this.from = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'from' field has been set */
    public boolean hasFrom() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'from' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearFrom() {
      from = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'to' field */
    public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getTo() {
      return to;
    }
    
    /** Sets the value of the 'to' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setTo(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
      validate(fields()[10], value);
      this.to = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'to' field has been set */
    public boolean hasTo() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'to' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearTo() {
      to = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'cc' field */
    public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getCc() {
      return cc;
    }
    
    /** Sets the value of the 'cc' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setCc(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
      validate(fields()[11], value);
      this.cc = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'cc' field has been set */
    public boolean hasCc() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'cc' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearCc() {
      cc = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'bcc' field */
    public java.util.List<com.elasticinbox.pipe.avro.AvroAddress> getBcc() {
      return bcc;
    }
    
    /** Sets the value of the 'bcc' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setBcc(java.util.List<com.elasticinbox.pipe.avro.AvroAddress> value) {
      validate(fields()[12], value);
      this.bcc = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'bcc' field has been set */
    public boolean hasBcc() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'bcc' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearBcc() {
      bcc = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'subject' field */
    public java.lang.CharSequence getSubject() {
      return subject;
    }
    
    /** Sets the value of the 'subject' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setSubject(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.subject = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'subject' field has been set */
    public boolean hasSubject() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'subject' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearSubject() {
      subject = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'plainBody' field */
    public java.lang.CharSequence getPlainBody() {
      return plainBody;
    }
    
    /** Sets the value of the 'plainBody' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setPlainBody(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.plainBody = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'plainBody' field has been set */
    public boolean hasPlainBody() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'plainBody' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearPlainBody() {
      plainBody = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'htmlBody' field */
    public java.lang.CharSequence getHtmlBody() {
      return htmlBody;
    }
    
    /** Sets the value of the 'htmlBody' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder setHtmlBody(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.htmlBody = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'htmlBody' field has been set */
    public boolean hasHtmlBody() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'htmlBody' field */
    public com.elasticinbox.pipe.avro.AvroMessage.Builder clearHtmlBody() {
      htmlBody = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    public AvroMessage build() {
      try {
        AvroMessage record = new AvroMessage();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.date = fieldSetFlags()[1] ? this.date : (java.lang.Long) defaultValue(fields()[1]);
        record.size = fieldSetFlags()[2] ? this.size : (java.lang.Long) defaultValue(fields()[2]);
        record.location = fieldSetFlags()[3] ? this.location : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.userId = fieldSetFlags()[4] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.labels = fieldSetFlags()[5] ? this.labels : (java.util.List<java.lang.Integer>) defaultValue(fields()[5]);
        record.markers = fieldSetFlags()[6] ? this.markers : (java.util.List<java.lang.Integer>) defaultValue(fields()[6]);
        record.properties = fieldSetFlags()[7] ? this.properties : (java.util.Map<java.lang.CharSequence,java.lang.Long>) defaultValue(fields()[7]);
        record.original = fieldSetFlags()[8] ? this.original : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.from = fieldSetFlags()[9] ? this.from : (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) defaultValue(fields()[9]);
        record.to = fieldSetFlags()[10] ? this.to : (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) defaultValue(fields()[10]);
        record.cc = fieldSetFlags()[11] ? this.cc : (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) defaultValue(fields()[11]);
        record.bcc = fieldSetFlags()[12] ? this.bcc : (java.util.List<com.elasticinbox.pipe.avro.AvroAddress>) defaultValue(fields()[12]);
        record.subject = fieldSetFlags()[13] ? this.subject : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.plainBody = fieldSetFlags()[14] ? this.plainBody : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.htmlBody = fieldSetFlags()[15] ? this.htmlBody : (java.lang.CharSequence) defaultValue(fields()[15]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
